// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC39CkwKVzfnpCwCNlf8qxEhFtzt4znadw',
    appId: '1:996423296243:web:2b580017c07cbabfa60386',
    messagingSenderId: '996423296243',
    projectId: 'flutter-study-8144f',
    authDomain: 'flutter-study-8144f.firebaseapp.com',
    storageBucket: 'flutter-study-8144f.firebasestorage.app',
    measurementId: 'G-EC0PJXKTJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjsOSl3i1HQZv_c9pU8hmSaKHSLI6Njkc',
    appId: '1:996423296243:android:876725d99540026aa60386',
    messagingSenderId: '996423296243',
    projectId: 'flutter-study-8144f',
    storageBucket: 'flutter-study-8144f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCxpXiPcguuyDQxEM3Rd7tCf3TgmCfp0',
    appId: '1:996423296243:ios:ae9b53e598800ed2a60386',
    messagingSenderId: '996423296243',
    projectId: 'flutter-study-8144f',
    storageBucket: 'flutter-study-8144f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCxpXiPcguuyDQxEM3Rd7tCf3TgmCfp0',
    appId: '1:996423296243:ios:ae9b53e598800ed2a60386',
    messagingSenderId: '996423296243',
    projectId: 'flutter-study-8144f',
    storageBucket: 'flutter-study-8144f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC39CkwKVzfnpCwCNlf8qxEhFtzt4znadw',
    appId: '1:996423296243:web:9914421916671005a60386',
    messagingSenderId: '996423296243',
    projectId: 'flutter-study-8144f',
    authDomain: 'flutter-study-8144f.firebaseapp.com',
    storageBucket: 'flutter-study-8144f.firebasestorage.app',
    measurementId: 'G-96KTB5MBSN',
  );

}